name: new_farmers_market_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  rxdart: ^0.20.0
  path_provider: ^1.4.0
  google_fonts: ^1.1.0
  flutter_gradients: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/background/
    - assets/appBar/
    - assets/images/bread/Baguette.jpg
    - assets/images/bread/Ciabatta.jpg
    - assets/images/bread/Croissant.jpg
    - assets/images/bread/GarlicBread.jpg
    - assets/images/bread/GingerBread.jpg
    - assets/images/bread/SourDough.jpg
    - assets/images/bread/TigerBread.jpg
    - assets/images/bread/TurkishBread.jpg
    - assets/images/bread/WholeWheat.jpg
    - assets/images/cakes/BlueberryCake.jpg
    - assets/images/cakes/CanoliCake.jpg
    - assets/images/cakes/CaramelCake.jpg
    - assets/images/cakes/CarrotCake.jpg
    - assets/images/cakes/CocaColaCake.jpg
    - assets/images/cakes/CoconutCake.jpg
    - assets/images/cakes/IcecreamCake.jpg
    - assets/images/cakes/OreoCake.jpg
    - assets/images/cakes/RaspberryCake.jpg
    - assets/images/cakes/VanillaCake.jpg
    - assets/images/cookies/BiscottiCookies.jpg
    - assets/images/cookies/GingerSnapsCookies.jpg
    - assets/images/cookies/KissCookies.jpg
    - assets/images/cookies/MolassesCookies.jpg
    - assets/images/cookies/OatmealRasinCookie.jpg
    - assets/images/cookies/PeanutButterCookies.jpg
    - assets/images/cookies/SnickerdoodlesCookies.jpg
    - assets/images/cookies/SnowballCookies.jpg
    - assets/images/cookies/WhoopiePiesCookies.jpg
    # - assets/images/cupcakes/cp1.jpg
    # - assets/images/cupcakes/cp2.jpg
    # - assets/images/cupcakes/cp3.jpg
    # - assets/images/cupcakes/cp4.jpg
    # - assets/images/cupcakes/cp5.jpg
    # - assets/images/cupcakes/cp6.jpg
    # - assets/images/cupcakes/cp7.jpg
    # - assets/images/cupcakes/cp8.jpg
    # - assets/images/cupcakes/cp9.jpg
    # - assets/images/cupcakes/cp10.jpg
    # - assets/images/donuts/donut1.jpg
    # - assets/images/donuts/donut2.jpg
    # - assets/images/donuts/donut3.jpg
    # - assets/images/donuts/donut4.jpg
    # - assets/images/donuts/donut5.jpg
    # - assets/images/donuts/donut6.jpg
    # - assets/images/donuts/donut7.jpg
    # - assets/images/donuts/donut8.jpg
    # - assets/images/donuts/donut9.jpg
    # - assets/images/donuts/donut10.jpg
    # - assets/images/donuts/donut1.jpg
    # - assets/images/sandwich/sandwich1.jpg
    # - assets/images/sandwich/sandwich2.jpg
    # - assets/images/sandwich/sandwich3.jpg
    # - assets/images/sandwich/sandwich4.jpg
    # - assets/images/sandwich/sandwich5.jpg
    # - assets/images/sandwich/sandwich6.jpg
    # - assets/images/sandwich/sandwich7.jpg
    # - assets/images/sandwich/sandwich8.jpg
    # - assets/images/sandwich/sandwich9.jpg
    # - assets/images/sandwich/sandwich10.jpg
 

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
